### ISSUE TITLE
学校名称在第二位无法正确选择，能否直接使用手机号登录

### ISSUE THREAD

**Issue by T-Atlas** [liulu1998/AnsRepeater#3]
![搜狗截图20年11月19日1012_1](https://user-images.githubusercontent.com/69239617/99612097-e6ece580-2a4f-11eb-9930-9afa27dae8ae.png)

**Comment by T-Atlas** [comment]
上面那个我解决了，但是进入问答列表后就不能用了
![Uploading 2020-11-19 10-36-31.png…]()

**Comment by T-Atlas** [comment]
上面那个我解决了，但是进入问答列表后就不能用了
![2020-11-19 10-36-31](https://user-images.githubusercontent.com/69239617/99613943-7778f500-2a53-11eb-8309-3c2865b3b511.png)

对于 学校不在列表第一位可以把这边改成对应的 列表位置排序-1 就行了
![2020-11-19 10-40-27](https://user-images.githubusercontent.com/69239617/99614058-ab541a80-2a53-11eb-99d4-469e7ffeb56c.png)

**Comment by liulu1998** [comment]
按照你的建议修复了**学校名** bug.

对于 ```失败!请检查网络状况```报错的问题, 尝试**提高**```main.py``` 18行 ```WAIT_TIME``` 的数值,或多运行几次.

**Comment by T-Atlas** [comment]
> 按照你的建议修复了**学校名** bug.
> 
> 对于 `失败!请检查网络状况`报错的问题, 尝试**提高**`main.py` 18行 `WAIT_TIME` 的数值,或多运行几次.

尝试了，还是不能用

**Comment by liulu1998** [comment]
> > 按照你的建议修复了**学校名** bug.
> > 对于 `失败!请检查网络状况`报错的问题, 尝试**提高**`main.py` 18行 `WAIT_TIME` 的数值,或多运行几次.
> 
> 尝试了，还是不能用

```gui``` 项设为 ```true```，看看模拟点击哪里出问题了

**Comment by T-Atlas** [comment]
> > > 按照你的建议修复了**学校名** bug.
> > > 对于 `失败!请检查网络状况`报错的问题, 尝试**提高**`main.py` 18行 `WAIT_TIME` 的数值,或多运行几次.
> > 
> > 
> > 尝试了，还是不能用
> 
> `gui` 项设为 `true`，看看模拟点击哪里出问题了

往下刷新问题列表，然后就报网络异常了，需要我提供info文件给你试一下吗

**Comment by liulu1998** [comment]
> > > > 按照你的建议修复了**学校名** bug.
> > > > 对于 `失败!请检查网络状况`报错的问题, 尝试**提高**`main.py` 18行 `WAIT_TIME` 的数值,或多运行几次.
> > > 
> > > 
> > > 尝试了，还是不能用
> > 
> > 
> > `gui` 项设为 `true`，看看模拟点击哪里出问题了
> 
> 往下刷新问题列表，然后就报网络异常了，需要我提供info文件给你试一下吗

可以，发我邮箱  liulu_heu@foxmail.com

**Comment by liulu1998** [comment]
已修复
